apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ecom
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
    version: blue
  ports:
    - port: 8304
      targetPort: 8304
      protocol: TCP
      name: http
  type: ClusterIP
