apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecom
  labels:
    app: order-service
spec:
  selector:
    app: order-service
    version: blue
  ports:
    - port: 8306
      targetPort: 8306
      protocol: TCP
      name: http
  type: ClusterIP
