apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecom
  labels:
    app: product-service
spec:
  selector:
    app: product-service
    version: blue
  ports:
    - port: 8305
      targetPort: 8305
      protocol: TCP
      name: http
  type: ClusterIP
