apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecom
  labels:
    app: user-service
spec:
  selector:
    app: user-service
    version: blue
  ports:
    - port: 8302
      targetPort: 8302
      protocol: TCP
      name: http
  type: ClusterIP
